# THIS IS A AUTOGENERATED FILE
from worlds_hardest_game.src.game.tile import Tile 
from worlds_hardest_game.src.game.enemy import Enemy 
from worlds_hardest_game.src.game.field import Field 


class LvlTest:
	def __init__(self):
		self.xStart = 50
		self.yStart = 50
		self.windowWidth = 1200
		self.windowHeight = 700
		self.numberOfTilesWidth = 22
		self.numberOfTilesHeight = 12
		self.tileSize = 50
		self.enemyColor = (0, 0, 255)
		self.field = Field(self.xStart, self.yStart, self.numberOfTilesWidth, self.numberOfTilesHeight, self.tileSize, self.enemyColor)
		self.fillTiles()
		self.fillEnemies()

	def fillTiles(self):
		self.field.field[0][0].outOfBounds = True
		self.field.field[0][1].outOfBounds = True
		self.field.field[0][1].wall = True
		self.field.field[0][1].edges = [False, True, False, False]
		self.field.field[0][2].outOfBounds = True
		self.field.field[0][2].wall = True
		self.field.field[0][2].edges = [False, True, False, False]
		self.field.field[0][3].outOfBounds = True
		self.field.field[0][3].wall = True
		self.field.field[0][3].edges = [False, True, False, False]
		self.field.field[0][4].outOfBounds = True
		self.field.field[0][4].wall = True
		self.field.field[0][4].edges = [False, True, False, False]
		self.field.field[0][5].outOfBounds = True
		self.field.field[0][5].wall = True
		self.field.field[0][5].edges = [False, True, False, False]
		self.field.field[0][6].outOfBounds = True
		self.field.field[0][6].wall = True
		self.field.field[0][6].edges = [False, True, False, False]
		self.field.field[0][7].outOfBounds = True
		self.field.field[0][7].wall = True
		self.field.field[0][7].edges = [False, True, False, False]
		self.field.field[0][8].outOfBounds = True
		self.field.field[0][8].wall = True
		self.field.field[0][8].edges = [False, True, False, False]
		self.field.field[0][9].outOfBounds = True
		self.field.field[0][9].wall = True
		self.field.field[0][9].edges = [False, True, False, False]
		self.field.field[0][10].outOfBounds = True
		self.field.field[0][10].wall = True
		self.field.field[0][10].edges = [False, True, False, False]
		self.field.field[0][11].outOfBounds = True
		self.field.field[1][0].outOfBounds = True
		self.field.field[1][0].wall = True
		self.field.field[1][0].edges = [False, False, True, False]
		self.field.field[1][1].safe = True
		self.field.field[1][2].safe = True
		self.field.field[1][3].safe = True
		self.field.field[1][4].safe = True
		self.field.field[1][5].safe = True
		self.field.field[1][6].safe = True
		self.field.field[1][7].safe = True
		self.field.field[1][8].safe = True
		self.field.field[1][11].outOfBounds = True
		self.field.field[1][11].wall = True
		self.field.field[1][11].edges = [True, False, False, False]
		self.field.field[2][0].outOfBounds = True
		self.field.field[2][0].wall = True
		self.field.field[2][0].edges = [False, False, True, False]
		self.field.field[2][1].safe = True
		self.field.field[2][2].safe = True
		self.field.field[2][3].safe = True
		self.field.field[2][4].safe = True
		self.field.field[2][5].safe = True
		self.field.field[2][6].safe = True
		self.field.field[2][7].safe = True
		self.field.field[2][8].safe = True
		self.field.field[2][11].outOfBounds = True
		self.field.field[2][11].wall = True
		self.field.field[2][11].edges = [True, False, False, False]
		self.field.field[3][0].outOfBounds = True
		self.field.field[3][1].outOfBounds = True
		self.field.field[3][1].wall = True
		self.field.field[3][1].edges = [False, False, False, True]
		self.field.field[3][2].outOfBounds = True
		self.field.field[3][2].wall = True
		self.field.field[3][2].edges = [False, False, False, True]
		self.field.field[3][3].outOfBounds = True
		self.field.field[3][3].wall = True
		self.field.field[3][3].edges = [False, False, False, True]
		self.field.field[3][4].outOfBounds = True
		self.field.field[3][4].wall = True
		self.field.field[3][4].edges = [False, False, False, True]
		self.field.field[3][5].outOfBounds = True
		self.field.field[3][5].wall = True
		self.field.field[3][5].edges = [False, False, False, True]
		self.field.field[3][6].outOfBounds = True
		self.field.field[3][6].wall = True
		self.field.field[3][6].edges = [False, False, False, True]
		self.field.field[3][7].outOfBounds = True
		self.field.field[3][7].wall = True
		self.field.field[3][7].edges = [False, False, False, True]
		self.field.field[3][8].outOfBounds = True
		self.field.field[3][8].wall = True
		self.field.field[3][8].edges = [False, False, True, True]
		self.field.field[3][11].outOfBounds = True
		self.field.field[3][11].wall = True
		self.field.field[3][11].edges = [True, False, False, False]
		self.field.field[4][0].outOfBounds = True
		self.field.field[4][1].outOfBounds = True
		self.field.field[4][1].wall = True
		self.field.field[4][1].edges = [False, True, False, False]
		self.field.field[4][2].outOfBounds = True
		self.field.field[4][2].wall = True
		self.field.field[4][2].edges = [False, True, False, False]
		self.field.field[4][3].outOfBounds = True
		self.field.field[4][3].wall = True
		self.field.field[4][3].edges = [False, True, False, False]
		self.field.field[4][4].outOfBounds = True
		self.field.field[4][4].wall = True
		self.field.field[4][4].edges = [False, True, False, False]
		self.field.field[4][5].outOfBounds = True
		self.field.field[4][5].wall = True
		self.field.field[4][5].edges = [False, True, False, False]
		self.field.field[4][6].outOfBounds = True
		self.field.field[4][6].wall = True
		self.field.field[4][6].edges = [False, True, False, False]
		self.field.field[4][7].outOfBounds = True
		self.field.field[4][7].wall = True
		self.field.field[4][7].edges = [False, True, False, False]
		self.field.field[4][8].outOfBounds = True
		self.field.field[4][8].wall = True
		self.field.field[4][8].edges = [False, True, True, False]
		self.field.field[4][11].outOfBounds = True
		self.field.field[4][11].wall = True
		self.field.field[4][11].edges = [True, False, False, False]
		self.field.field[5][0].outOfBounds = True
		self.field.field[5][0].wall = True
		self.field.field[5][0].edges = [False, False, True, False]
		self.field.field[5][11].outOfBounds = True
		self.field.field[5][11].wall = True
		self.field.field[5][11].edges = [True, False, False, False]
		self.field.field[6][0].outOfBounds = True
		self.field.field[6][0].wall = True
		self.field.field[6][0].edges = [False, False, True, False]
		self.field.field[6][11].outOfBounds = True
		self.field.field[6][11].wall = True
		self.field.field[6][11].edges = [True, False, False, False]
		self.field.field[7][0].outOfBounds = True
		self.field.field[7][0].wall = True
		self.field.field[7][0].edges = [False, False, True, False]
		self.field.field[7][11].outOfBounds = True
		self.field.field[7][11].wall = True
		self.field.field[7][11].edges = [True, False, False, False]
		self.field.field[8][0].outOfBounds = True
		self.field.field[8][1].outOfBounds = True
		self.field.field[8][1].wall = True
		self.field.field[8][1].edges = [False, False, False, True]
		self.field.field[8][2].outOfBounds = True
		self.field.field[8][2].wall = True
		self.field.field[8][2].edges = [False, False, True, True]
		self.field.field[8][9].outOfBounds = True
		self.field.field[8][9].wall = True
		self.field.field[8][9].edges = [True, False, False, True]
		self.field.field[8][10].outOfBounds = True
		self.field.field[8][10].wall = True
		self.field.field[8][10].edges = [False, False, False, True]
		self.field.field[8][11].outOfBounds = True
		self.field.field[9][0].outOfBounds = True
		self.field.field[9][1].outOfBounds = True
		self.field.field[9][2].outOfBounds = True
		self.field.field[9][3].outOfBounds = True
		self.field.field[9][3].wall = True
		self.field.field[9][3].edges = [False, False, True, True]
		self.field.field[9][8].outOfBounds = True
		self.field.field[9][8].wall = True
		self.field.field[9][8].edges = [True, False, False, True]
		self.field.field[9][9].outOfBounds = True
		self.field.field[9][10].outOfBounds = True
		self.field.field[9][11].outOfBounds = True
		self.field.field[10][0].outOfBounds = True
		self.field.field[10][1].outOfBounds = True
		self.field.field[10][2].outOfBounds = True
		self.field.field[10][3].outOfBounds = True
		self.field.field[10][4].outOfBounds = True
		self.field.field[10][4].wall = True
		self.field.field[10][4].edges = [False, True, True, True]
		self.field.field[10][7].outOfBounds = True
		self.field.field[10][7].wall = True
		self.field.field[10][7].edges = [True, True, False, True]
		self.field.field[10][8].outOfBounds = True
		self.field.field[10][9].outOfBounds = True
		self.field.field[10][10].outOfBounds = True
		self.field.field[10][11].outOfBounds = True
		self.field.field[11][0].outOfBounds = True
		self.field.field[11][1].outOfBounds = True
		self.field.field[11][2].outOfBounds = True
		self.field.field[11][3].outOfBounds = True
		self.field.field[11][3].wall = True
		self.field.field[11][3].edges = [False, True, True, False]
		self.field.field[11][8].outOfBounds = True
		self.field.field[11][8].wall = True
		self.field.field[11][8].edges = [True, True, False, False]
		self.field.field[11][9].outOfBounds = True
		self.field.field[11][10].outOfBounds = True
		self.field.field[11][11].outOfBounds = True
		self.field.field[12][0].outOfBounds = True
		self.field.field[12][1].outOfBounds = True
		self.field.field[12][1].wall = True
		self.field.field[12][1].edges = [False, True, False, False]
		self.field.field[12][2].outOfBounds = True
		self.field.field[12][2].wall = True
		self.field.field[12][2].edges = [False, True, True, False]
		self.field.field[12][9].outOfBounds = True
		self.field.field[12][9].wall = True
		self.field.field[12][9].edges = [True, True, False, False]
		self.field.field[12][10].outOfBounds = True
		self.field.field[12][10].wall = True
		self.field.field[12][10].edges = [False, True, False, False]
		self.field.field[12][11].outOfBounds = True
		self.field.field[13][0].outOfBounds = True
		self.field.field[13][0].wall = True
		self.field.field[13][0].edges = [False, False, True, False]
		self.field.field[13][11].outOfBounds = True
		self.field.field[13][11].wall = True
		self.field.field[13][11].edges = [True, False, False, False]
		self.field.field[14][0].outOfBounds = True
		self.field.field[14][0].wall = True
		self.field.field[14][0].edges = [False, False, True, False]
		self.field.field[14][11].outOfBounds = True
		self.field.field[14][11].wall = True
		self.field.field[14][11].edges = [True, False, False, False]
		self.field.field[15][0].outOfBounds = True
		self.field.field[15][0].wall = True
		self.field.field[15][0].edges = [False, False, True, False]
		self.field.field[15][11].outOfBounds = True
		self.field.field[15][11].wall = True
		self.field.field[15][11].edges = [True, False, False, False]
		self.field.field[16][0].outOfBounds = True
		self.field.field[16][0].wall = True
		self.field.field[16][0].edges = [False, False, True, False]
		self.field.field[16][11].outOfBounds = True
		self.field.field[16][11].wall = True
		self.field.field[16][11].edges = [True, False, False, False]
		self.field.field[17][0].outOfBounds = True
		self.field.field[17][0].wall = True
		self.field.field[17][0].edges = [False, False, True, False]
		self.field.field[17][3].outOfBounds = True
		self.field.field[17][3].wall = True
		self.field.field[17][3].edges = [True, False, False, True]
		self.field.field[17][4].outOfBounds = True
		self.field.field[17][4].wall = True
		self.field.field[17][4].edges = [False, False, False, True]
		self.field.field[17][5].outOfBounds = True
		self.field.field[17][5].wall = True
		self.field.field[17][5].edges = [False, False, False, True]
		self.field.field[17][6].outOfBounds = True
		self.field.field[17][6].wall = True
		self.field.field[17][6].edges = [False, False, False, True]
		self.field.field[17][7].outOfBounds = True
		self.field.field[17][7].wall = True
		self.field.field[17][7].edges = [False, False, False, True]
		self.field.field[17][8].outOfBounds = True
		self.field.field[17][8].wall = True
		self.field.field[17][8].edges = [False, False, False, True]
		self.field.field[17][9].outOfBounds = True
		self.field.field[17][9].wall = True
		self.field.field[17][9].edges = [False, False, False, True]
		self.field.field[17][10].outOfBounds = True
		self.field.field[17][10].wall = True
		self.field.field[17][10].edges = [False, False, False, True]
		self.field.field[17][11].outOfBounds = True
		self.field.field[18][0].outOfBounds = True
		self.field.field[18][0].wall = True
		self.field.field[18][0].edges = [False, False, True, False]
		self.field.field[18][3].outOfBounds = True
		self.field.field[18][3].wall = True
		self.field.field[18][3].edges = [True, True, False, False]
		self.field.field[18][4].outOfBounds = True
		self.field.field[18][4].wall = True
		self.field.field[18][4].edges = [False, True, False, False]
		self.field.field[18][5].outOfBounds = True
		self.field.field[18][5].wall = True
		self.field.field[18][5].edges = [False, True, False, False]
		self.field.field[18][6].outOfBounds = True
		self.field.field[18][6].wall = True
		self.field.field[18][6].edges = [False, True, False, False]
		self.field.field[18][7].outOfBounds = True
		self.field.field[18][7].wall = True
		self.field.field[18][7].edges = [False, True, False, False]
		self.field.field[18][8].outOfBounds = True
		self.field.field[18][8].wall = True
		self.field.field[18][8].edges = [False, True, False, False]
		self.field.field[18][9].outOfBounds = True
		self.field.field[18][9].wall = True
		self.field.field[18][9].edges = [False, True, False, False]
		self.field.field[18][10].outOfBounds = True
		self.field.field[18][10].wall = True
		self.field.field[18][10].edges = [False, True, False, False]
		self.field.field[18][11].outOfBounds = True
		self.field.field[19][0].outOfBounds = True
		self.field.field[19][0].wall = True
		self.field.field[19][0].edges = [False, False, True, False]
		self.field.field[19][3].goal = True
		self.field.field[19][4].goal = True
		self.field.field[19][5].goal = True
		self.field.field[19][6].goal = True
		self.field.field[19][7].goal = True
		self.field.field[19][8].goal = True
		self.field.field[19][9].goal = True
		self.field.field[19][10].goal = True
		self.field.field[19][11].outOfBounds = True
		self.field.field[19][11].wall = True
		self.field.field[19][11].edges = [True, False, False, False]
		self.field.field[20][0].outOfBounds = True
		self.field.field[20][0].wall = True
		self.field.field[20][0].edges = [False, False, True, False]
		self.field.field[20][3].goal = True
		self.field.field[20][4].goal = True
		self.field.field[20][5].goal = True
		self.field.field[20][6].goal = True
		self.field.field[20][7].goal = True
		self.field.field[20][8].goal = True
		self.field.field[20][9].goal = True
		self.field.field[20][10].goal = True
		self.field.field[20][11].outOfBounds = True
		self.field.field[20][11].wall = True
		self.field.field[20][11].edges = [True, False, False, False]
		self.field.field[21][0].outOfBounds = True
		self.field.field[21][1].outOfBounds = True
		self.field.field[21][1].wall = True
		self.field.field[21][1].edges = [False, False, False, True]
		self.field.field[21][2].outOfBounds = True
		self.field.field[21][2].wall = True
		self.field.field[21][2].edges = [False, False, False, True]
		self.field.field[21][3].outOfBounds = True
		self.field.field[21][3].wall = True
		self.field.field[21][3].edges = [False, False, False, True]
		self.field.field[21][4].outOfBounds = True
		self.field.field[21][4].wall = True
		self.field.field[21][4].edges = [False, False, False, True]
		self.field.field[21][5].outOfBounds = True
		self.field.field[21][5].wall = True
		self.field.field[21][5].edges = [False, False, False, True]
		self.field.field[21][6].outOfBounds = True
		self.field.field[21][6].wall = True
		self.field.field[21][6].edges = [False, False, False, True]
		self.field.field[21][7].outOfBounds = True
		self.field.field[21][7].wall = True
		self.field.field[21][7].edges = [False, False, False, True]
		self.field.field[21][8].outOfBounds = True
		self.field.field[21][8].wall = True
		self.field.field[21][8].edges = [False, False, False, True]
		self.field.field[21][9].outOfBounds = True
		self.field.field[21][9].wall = True
		self.field.field[21][9].edges = [False, False, False, True]
		self.field.field[21][10].outOfBounds = True
		self.field.field[21][10].wall = True
		self.field.field[21][10].edges = [False, False, False, True]
		self.field.field[21][11].outOfBounds = True

	def fillEnemies(self):
		interEnemy = Enemy(425, 525, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(125, 525)])
		self.field.enemy.append(interEnemy)
		interEnemy = Enemy(325, 125, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(325, 575)])
		self.field.enemy.append(interEnemy)
		interEnemy = Enemy(375, 575, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(375, 125)])
		self.field.enemy.append(interEnemy)
		interEnemy = Enemy(425, 125, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(425, 575)])
		self.field.enemy.append(interEnemy)
		interEnemy = Enemy(325, 325, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(875, 325)])
		self.field.enemy.append(interEnemy)
		interEnemy = Enemy(875, 375, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(325, 375)])
		self.field.enemy.append(interEnemy)
		interEnemy = Enemy(725, 575, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(725, 175)])
		self.field.enemy.append(interEnemy)
		interEnemy = Enemy(825, 575, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(825, 175)])
		self.field.enemy.append(interEnemy)
		interEnemy = Enemy(775, 125, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(775, 525)])
		self.field.enemy.append(interEnemy)
		interEnemy = Enemy(875, 125, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(875, 525)])
		self.field.enemy.append(interEnemy)
		interEnemy = Enemy(725, 175, 15, 10, (0, 0, 255))
		interEnemy.addMovementPoints([(1075, 175)])
		self.field.enemy.append(interEnemy)

	def draw(self, screen):
		self.field.draw(screen)

